#!/bin/bash
#
# sensing.sh - Wi-Fi motion map for the CB0401, in one command.
#
# The router measures how its radio channel to connected devices changes
# (CFR capture, router/cfr-trigger + router/cfr_capture_daemon.sh); when
# someone moves between the router and a device, that channel fluctuates.
# ./sensing (Go, this repo) pulls the captures over SSH, measures each
# link against its own normal level, and serves a floor plan you draw
# yourself - walls, router, devices - on which links light up and a dot
# glows where the movement is, in 2D or 3D. Devices you don't place show as
# a ring at their distance from the router (signal strength).
#
# Every run, idempotently:
#   1. Installs/refreshes cfr-trigger and the capture daemon on the router
#      (uploads only what changed). Capture runs only while this script
#      runs and stops, with the firmware's CFR timer off, when you quit.
#   2. Builds ./sensing/sensing and starts it on http://localhost:3000.
#   3. Unless --local: opens a Cloudflare quick tunnel and sends the link
#      (with a per-run access key) through the ntfy/Telegram backend
#      setup.sh configured in gui/.env.
#
# Anchors: the devices the router measures against. Movement is seen on
# the path between the router and each anchor, so anchors must never move
# (TV, desktop, vacuum on its dock, smart lamp) - a phone's or laptop's link
# changes whenever its owner moves. Every run lists the connected devices,
# pre-ticks the ones that look stationary (name, how steady their signal
# is), and lets you change the choice; it is remembered on the router and
# kept automatically after 20 s without input.
#
# Usage: ./sensing.sh [--anchors mac,mac,...] [--local]
#                     [--threshold 3] [--no-router-install]
#                     [--router-ip 192.168.31.1] [--router-key path] [--env-file path]
#
#   --anchors LIST     set the anchors without the menu (comma-separated MACs)
#   --local            no tunnel - nothing leaves this machine
#   --threshold X      how far above its normal level a link must go to
#                      count as movement, in dB (default 3)
#
set -e
cd "$(dirname "$0")"
REPO_DIR="$(pwd)"

ROUTER_IP="${ROUTER_IP:-192.168.31.1}"
ROUTER_KEY=""
ENV_FILE=""
PUBLIC=1
ROUTER_INSTALL=1
SET_ANCHORS=""
THRESHOLD="3"
HTTP_PORT="${SENSING_PORT:-3000}"
PUBLIC_PORT="${SENSING_PUBLIC_PORT:-3080}"
while [ $# -gt 0 ]; do
  case "$1" in
  --router-ip) ROUTER_IP="$2"; shift 2 ;;
  --router-key) ROUTER_KEY="$2"; shift 2 ;;
  --env-file) ENV_FILE="$2"; shift 2 ;;
  --local) PUBLIC=0; shift ;;
  --public) PUBLIC=1; shift ;;
  --no-router-install) ROUTER_INSTALL=0; shift ;;
  --threshold) THRESHOLD="$2"; shift 2 ;;
  --anchors) SET_ANCHORS="$(echo "$2" | tr 'A-F,' 'a-f ')"; shift 2 ;;
  --band|--links) echo "$1 is gone: pick the devices to capture in the anchor menu (or --anchors)" >&2; exit 2 ;;
  -h|--help) sed -n '2,/^set -e/p' "$0" | sed 's/^# \{0,1\}//' | sed '$d'; exit 0 ;;
  *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

# router_key and gui/.env are generated by setup.sh and gitignored, so they
# live in the checkout setup.sh ran in - or, from a git worktree, three
# levels up.
find_local_file() {
  for candidate in "$REPO_DIR/gui/$1" "$REPO_DIR/../../../gui/$1"; do
    if [ -f "$candidate" ]; then echo "$candidate"; return 0; fi
  done
  return 1
}
[ -n "$ROUTER_KEY" ] || ROUTER_KEY="$(find_local_file router_key || true)"
if [ -z "$ROUTER_KEY" ] || [ ! -f "$ROUTER_KEY" ]; then
  echo "Router SSH key not found - run ./start.sh first (or pass --router-key)." >&2
  exit 1
fi
[ -n "$ENV_FILE" ] || ENV_FILE="$(find_local_file .env || true)"
command -v go >/dev/null 2>&1 || { echo "Go not found. Install it first: https://go.dev/dl/" >&2; exit 1; }
if [ "$PUBLIC" = 1 ] && ! command -v cloudflared >/dev/null 2>&1; then
  echo "The public link needs cloudflared: brew install cloudflared (or run with --local)." >&2
  exit 1
fi

for port in "$HTTP_PORT" "$PUBLIC_PORT"; do
  owner="$(lsof -nP -iTCP:"$port" -sTCP:LISTEN 2>/dev/null | awk 'NR>1 {print $2 " (" $1 ")"}' | sort -u | tr '\n' ' ')"
  if [ -n "$owner" ]; then
    echo "Port $port is already in use by pid $owner - stop that first." >&2
    exit 1
  fi
done

say() { echo; echo "=== $* ==="; }

SSH_OPTS=(-i "$ROUTER_KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa -o ConnectTimeout=5 -o BatchMode=yes)
ssh_router() { ssh "${SSH_OPTS[@]}" "root@$ROUTER_IP" "$@"; }
scp_to_router() {
  local err
  err="$(scp -O "${SSH_OPTS[@]}" "$@" 2>&1)" && return 0
  if echo "$err" | grep -qi 'unknown option'; then scp "${SSH_OPTS[@]}" "$@"; else echo "$err" >&2; return 1; fi
}
file_sum() { if command -v md5sum >/dev/null 2>&1; then md5sum "$1" | cut -d' ' -f1; else md5 -q "$1"; fi; }

if ! ssh_router true 2>/dev/null; then
  echo "The router at $ROUTER_IP doesn't accept this toolkit's SSH key. Run ./start.sh once, then rerun this." >&2
  exit 1
fi

# notifications through whatever setup.sh configured (ntfy or Telegram)
NOTIFY_READY=0
if [ -n "$ENV_FILE" ] && [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1091
  . "$REPO_DIR/router/notify_common.sh"
  NOTIFY_BACKEND="$(grep '^NOTIFY_BACKEND=' "$ENV_FILE" | cut -d= -f2-)"
  NTFY_TOPIC="$(grep '^NTFY_TOPIC=' "$ENV_FILE" | cut -d= -f2-)"
  TELEGRAM_BOT_TOKEN="$(grep '^TELEGRAM_BOT_TOKEN=' "$ENV_FILE" | cut -d= -f2-)"
  TELEGRAM_CHAT_ID="$(grep '^TELEGRAM_CHAT_ID=' "$ENV_FILE" | cut -d= -f2-)"
  NOTIFY_BACKEND="${NOTIFY_BACKEND:-ntfy}"
  NOTIFY_READY=1
fi

if [ "$ROUTER_INSTALL" = 1 ]; then
  say "Router: CFR capture (cfr-trigger + cfr_capture_daemon.sh)"
  TMP_DIR="$(mktemp -d)"
  ( cd "$REPO_DIR/router/cfr-trigger" && CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="-s -w" -o "$TMP_DIR/cfr-trigger" . )
  cp "$REPO_DIR/router/cfr_capture_daemon.sh" "$TMP_DIR/cfr_capture_daemon.sh"
  want="$(file_sum "$TMP_DIR/cfr-trigger") $(file_sum "$TMP_DIR/cfr_capture_daemon.sh")"
  have="$(ssh_router 'cd /etc/crontabs/patches 2>/dev/null && md5sum cfr-trigger cfr_capture_daemon.sh 2>/dev/null | cut -d" " -f1 | tr "\n" " " | sed "s/ $//"' 2>/dev/null || true)"
  if [ "$want" = "$have" ]; then
    echo "already up to date"
  else
    scp_to_router "$TMP_DIR/cfr-trigger" "$TMP_DIR/cfr_capture_daemon.sh" "root@$ROUTER_IP:/tmp/" >/dev/null
    ssh_router 'mkdir -p /etc/crontabs/patches
      sh /etc/crontabs/patches/cfr_capture_daemon.sh --stop 2>/dev/null
      mv /tmp/cfr-trigger /tmp/cfr_capture_daemon.sh /etc/crontabs/patches/
      chmod +x /etc/crontabs/patches/cfr-trigger /etc/crontabs/patches/cfr_capture_daemon.sh'
    echo "installed"
  fi
  rm -rf "$TMP_DIR"
  # Older installs ran capture permanently from cron; with nobody collecting
  # the captures that filled the router's RAM and rebooted it. Remove it.
  ssh_router 'if grep -q cfr_capture_daemon /etc/crontabs/root 2>/dev/null; then
      sed -i "/cfr_capture_daemon/d" /etc/crontabs/root; /etc/init.d/cron restart >/dev/null 2>&1 || true
    fi'
fi
say "Anchors: devices that never move"
CONF=/etc/crontabs/patches/cfr_capture.conf
SAVED="$(ssh_router "sed -n 's/^PEERS=\"\\(.*\\)\"/\\1/p' $CONF 2>/dev/null" || true)"
# Four listings 2 s apart: how much each device's signal wobbles.
ST_FILE="$(mktemp)"
for i in 1 2 3 4; do
  ssh_router 'sh /etc/crontabs/patches/cfr_capture_daemon.sh --stations' >>"$ST_FILE" 2>/dev/null || true
  [ "$i" = 4 ] || sleep 2
done
# one line per device: mac ghz rssi_min rssi_max psmode name verdict
DEVICES="$(awk '
  { mac = $3; if (!(mac in g)) { order[++n] = mac; lo[mac] = 999; hi[mac] = -999 }
    g[mac] = $2; ps[mac] = $5; nm[mac] = $7
    if ($4 < lo[mac]) lo[mac] = $4; if ($4 > hi[mac]) hi[mac] = $4 }
  END { for (i = 1; i <= n; i++) { m = order[i]; name = tolower(nm[m]); v = "unsure"
      if (name ~ /iphone|ipad|android|honor|galaxy|pixel|redmi-?note|oneplus|phone|macbook|laptop|notebook|watch|huawei|poco/) v = "moves"
      else if (name ~ /roborock|vacuum|dreame|robot|light|bulb|lamp|tv|television|bravia|lg-?webos|mac-?mini|^mac$|imac|desktop|printer|plug|socket|camera|speaker|homepod|echo|nest|chromecast|appletv|nas|esp|tasmota|shelly|yeelight|miio|fridge|washer|conditioner/) v = "still"
      else if (hi[m] - lo[m] >= 6) v = "moves"
      print m, g[m], lo[m], hi[m], ps[m], nm[m], v } }' "$ST_FILE")"
rm -f "$ST_FILE"
if [ -z "$DEVICES" ]; then
  echo "No devices connected to the router - nothing to measure against." >&2
  exit 1
fi
if [ -n "$SET_ANCHORS" ]; then
  CHOSEN="$SET_ANCHORS"
elif [ -n "$SAVED" ]; then
  CHOSEN="$SAVED"
else
  CHOSEN="$(echo "$DEVICES" | awk '$7 == "still" {print $1}' | head -4 | tr '\n' ' ')"
fi
show_menu() {
  local i=0
  echo "$DEVICES" | while read -r mac ghz lo hi psm name verdict; do
    i=$((i + 1))
    mark="[ ]"; case " $CHOSEN " in *" $mac "*) mark="[x]" ;; esac
    band="5 GHz"; case "$ghz" in 2*) band="2.4 GHz" ;; esac
    note=""
    case "$verdict" in still) note="stationary" ;; moves) note="moves with people" ;; *) note="?" ;; esac
    [ "$psm" != 0 ] && note="$note, power save (may give fewer captures)"
    [ $((hi - lo)) -ge 6 ] && note="$note, signal wobbled ${lo}..${hi} dBm"
    printf "  %s %d  %-26s %-8s %4s dBm  %s\n" "$mark" "$i" "$name" "$band" "$hi" "$note"
  done
}
if [ -z "$SET_ANCHORS" ] && [ -t 0 ]; then
  first=1
  while :; do
    show_menu
    if [ "$first" = 1 ]; then
      printf "Numbers to tick/untick (e.g. 2 5), Enter to go on (keeps this choice in 20 s): "
      if ! read -r -t 20 answer; then echo; answer=""; fi
      first=0
    else
      printf "Numbers to tick/untick, Enter to go on: "
      read -r answer || answer=""
    fi
    [ -n "$answer" ] || break
    for n in $answer; do
      mac="$(echo "$DEVICES" | sed -n "${n}p" | cut -d' ' -f1)"
      [ -n "$mac" ] || continue
      case " $CHOSEN " in
      *" $mac "*) CHOSEN="$(echo " $CHOSEN " | sed "s/ $mac / /" | xargs)" ;;
      *) CHOSEN="$(echo "$CHOSEN $mac" | xargs)" ;;
      esac
    done
    echo
  done
else
  show_menu
fi
CHOSEN="$(echo "$CHOSEN" | xargs)"
N_ANCHORS="$(echo "$CHOSEN" | wc -w | tr -d ' ')"
if [ "$N_ANCHORS" = 0 ]; then
  echo "No anchors chosen - nothing to measure against." >&2
  exit 1
fi
[ "$N_ANCHORS" -gt 4 ] && echo "Note: the router's firmware handled 4 captured devices in testing; more may be refused."
# Capture rate: ~220 captures/s per device with one 5 GHz anchor. 5 GHz
# records are 8.4 KB and the SSH link carries ~4 MB/s, so share it.
N5=0
for mac in $CHOSEN; do
  echo "$DEVICES" | awk -v m="$mac" '$1 == m && $2 !~ /^2/ {f = 1} END {exit !f}' && N5=$((N5 + 1))
done
PERIOD=3; [ "$N5" -ge 2 ] && PERIOD=5; [ "$N5" -ge 3 ] && PERIOD=8
ssh_router "touch $CONF; sed -i '/^BAND=/d; /^PEERS=/d; /^MAX_PEERS=/d; /^PERIODICITY_MS=/d' $CONF
  printf 'BAND=both\nPEERS=\"%s\"\nMAX_PEERS=%s\nPERIODICITY_MS=%s\n' '$CHOSEN' '$N_ANCHORS' '$PERIOD' >> $CONF"
if [ "$CHOSEN" != "$SAVED" ] && [ -n "$SAVED" ]; then
  # a running daemon keeps its old settings; the map isn't running yet
  ssh_router 'sh /etc/crontabs/patches/cfr_capture_daemon.sh --stop' >/dev/null 2>&1 || true
fi
echo "anchors: $(for mac in $CHOSEN; do echo "$DEVICES" | awk -v m="$mac" '$1 == m {print $6}'; done | tr '\n' ' ')(capture every ${PERIOD} ms)"

say "Building the motion map"
( cd "$REPO_DIR/sensing" && go build -o sensing . )

PIDS=""
CAPTURE_STARTED=0
cleanup() {
  trap - EXIT INT TERM HUP
  echo
  echo "Stopping..."
  # shellcheck disable=SC2086
  [ -n "$PIDS" ] && kill $PIDS 2>/dev/null
  if [ "$CAPTURE_STARTED" = 1 ]; then
    ssh_router 'sh /etc/crontabs/patches/cfr_capture_daemon.sh --stop' 2>/dev/null \
      && echo "capture stopped on the router" \
      || echo "(couldn't reach the router to stop capture - it stops by itself within a minute, as nothing collects it)"
  fi
}
trap cleanup EXIT INT TERM HUP # HUP: the terminal window was closed

say "Starting capture on the router"
ssh_router 'sh /etc/crontabs/patches/cfr_capture_daemon.sh --ensure' || { echo "Couldn't start CFR capture on the router." >&2; exit 1; }
CAPTURE_STARTED=1

ACCESS_KEY=""
SENSING_ARGS=(-key "$ROUTER_KEY" -host "root@$ROUTER_IP" -listen "127.0.0.1:$HTTP_PORT" -plan "$REPO_DIR/data/plan.json" -threshold "$THRESHOLD")
if [ "$PUBLIC" = 1 ]; then
  ACCESS_KEY="$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  SENSING_ARGS+=(-public "127.0.0.1:$PUBLIC_PORT" -access-key "$ACCESS_KEY")
fi
"$REPO_DIR/sensing/sensing" "${SENSING_ARGS[@]}" > /tmp/sensing.log 2>&1 &
PIDS="$PIDS $!"
sleep 1
if ! kill -0 "$!" 2>/dev/null; then
  echo "The motion map exited right away - /tmp/sensing.log ends with:" >&2
  tail -5 /tmp/sensing.log >&2
  exit 1
fi

PUBLIC_LINK=""
if [ "$PUBLIC" = 1 ]; then
  say "Public link (Cloudflare quick tunnel)"
  cloudflared tunnel --url "http://127.0.0.1:$PUBLIC_PORT" --no-autoupdate > /tmp/sensing-cloudflared.log 2>&1 &
  TUNNEL_PID=$!
  PIDS="$PIDS $TUNNEL_PID"
  PUBLIC_URL=""
  for _ in $(seq 1 40); do
    PUBLIC_URL="$(grep -o 'https://[a-z0-9-]*\.trycloudflare\.com' /tmp/sensing-cloudflared.log 2>/dev/null | head -1 || true)"
    [ -n "$PUBLIC_URL" ] && break
    kill -0 "$TUNNEL_PID" 2>/dev/null || break
    sleep 1
  done
  if [ -n "$PUBLIC_URL" ]; then
    PUBLIC_LINK="$PUBLIC_URL/?k=$ACCESS_KEY"
    echo "$PUBLIC_LINK"
    if [ "$NOTIFY_READY" = 1 ] && notify "Motion map" "satellite" "$PUBLIC_LINK
Live while sensing.sh runs on $(hostname). Anyone with this exact link can open it - don't forward it."; then
      echo "Link sent via $NOTIFY_BACKEND."
    else
      echo "(link not sent - no ntfy/Telegram configured, or sending failed; copy it from above)"
    fi
  else
    echo "cloudflared didn't report a tunnel URL - /tmp/sensing-cloudflared.log ends with:" >&2
    tail -3 /tmp/sensing-cloudflared.log >&2
  fi
fi

DASHBOARD_URL="http://localhost:$HTTP_PORT/"
if command -v open >/dev/null 2>&1; then open "$DASHBOARD_URL"
elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$DASHBOARD_URL"
fi
echo
echo "Running. Map: $DASHBOARD_URL"
[ -n "$PUBLIC_LINK" ] && echo "Public: $PUBLIC_LINK"
echo "First time: click 'Edit plan', draw the walls, place the router and devices."
echo "Press Ctrl+C, or close this terminal, to stop (capture on the router stops too)."
# shellcheck disable=SC2086
wait $PIDS
